### ISSUE TITLE
ClassNotFound when launchig sarlc with -C --xml

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1007]
When launching `sarlc -C --xml`, the following error occurs:
```
ERROR com/fasterxml/jackson/core/TSFBuilder
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/TSFBuilder
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:122)
	at org.arakhne.afc.bootique.printconfig.commands.PrintConfigCommand.generateXml(PrintConfigCommand.java:177)
	at org.arakhne.afc.bootique.printconfig.commands.PrintConfigCommand.run(PrintConfigCommand.java:121)
	at io.bootique.run.DefaultRunner.run(DefaultRunner.java:43)
	at io.bootique.BQRuntime.run(BQRuntime.java:85)
	at io.sarl.maven.bootiqueapp.BootiqueMain.runCommand(BootiqueMain.java:140)
	at io.sarl.lang.sarlc.Main.run(Main.java:65)
	at io.sarl.lang.sarlc.Main.main(Main.java:53)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.TSFBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more
```

**Comment by gallandarakhneorg** [comment]
Cause: https://github.com/gallandarakhneorg/afc/issues/185
