### ISSUE TITLE
xtext validation error

### ISSUE THREAD

**Issue by abdkaci** [sarl/sarl#1041]
!ENTRY org.eclipse.jface.text 4 0 2020-12-14 17:54:06.888
!MESSAGE org.eclipse.core.runtime.OperationCanceledException
!STACK 0
java.util.concurrent.CompletionException: org.eclipse.core.runtime.OperationCanceledException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: org.eclipse.core.runtime.OperationCanceledException
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:539)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:496)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:135)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:49)
	at org.eclipse.xtext.ui.codemining.AbstractXtextCodeMiningProvider.lambda$0(AbstractXtextCodeMiningProvider.java:89)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 5 more

**Comment by gallandarakhneorg** [comment]
According to the stack trace, the problem may be caused by the code-mining feature.

As a possible work-around, this editor's feature for helping the developpers may be disabled into the general preferences: `Windows > Preferences > SARL > Editor`, uncheck the codemining feature.

**Comment by gallandarakhneorg** [comment]
Since the reported issue does not contains the root cause of the error, that is at the origin of the failure of the code mining, it is impossible to totally fix this issue.
Nevertheless, we update the code of the code mining generator in order to:

* report the cause of the error in a dialog box and in the Eclipse logs;
* disable temporarely the code mining feature until the next reboot of the SARL devleopment environment.
