### ISSUE TITLE
No SRE into the SARL product on Windows 10 and Ubuntu 2020

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1064]
When launching SARL product on a Windows 10 OS with JDK 11, the SRE does not appear into the list of installed SRE.

```
!SESSION 2021-03-01 11:54:37.294 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.10
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY io.janusproject.eclipse 4 0 2021-03-01 11:54:38.653
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: io.janusproject.eclipse [24]
  Unresolved requirement: Require-Bundle: io.janusproject.plugin; bundle-version="0.11.0"; visibility:="reexport"
    -> Bundle-SymbolicName: io.janusproject.plugin; bundle-version="0.11.0"; singleton:="true"
       io.janusproject.plugin [25]
         Unresolved requirement: Require-Bundle: com.fasterxml.jackson.dataformat.jackson-dataformat-xml; bundle-version="2.10.1"
           -> Bundle-SymbolicName: com.fasterxml.jackson.dataformat.jackson-dataformat-xml; bundle-version="2.11.0"
              com.fasterxml.jackson.dataformat.jackson-dataformat-xml [7]
                Unresolved requirement: Import-Package: com.fasterxml.jackson.module.jaxb; version="[2.11.0,3.0.0)"
                  -> Export-Package: com.fasterxml.jackson.module.jaxb; bundle-symbolic-name="com.fasterxml.jackson.module.jackson-module-jaxb-annotations"; bundle-version="2.11.0"; version="2.11.0"; uses:="com.fasterxml.jackson.annotation,com.fasterxml.jackson.core,com.fasterxml.jackson.databind,com.fasterxml.jackson.databind.cfg,com.fasterxml.jackson.databind.introspect,com.fasterxml.jackson.databind.jsontype,com.fasterxml.jackson.databind.type,com.fasterxml.jackson.databind.util,javax.xml.bind.annotation,javax.xml.bind.annotation.adapters"
                     com.fasterxml.jackson.module.jackson-module-jaxb-annotations [9]
                       Unresolved requirement: Import-Package: javax.activation; version="[1.2.0,2.0.0)"; resolution:="optional"
                       Unresolved requirement: Import-Package: javax.xml.bind; version="[2.3.0,3.0.0)"
                         -> Export-Package: javax.xml.bind; bundle-symbolic-name="jakarta.xml.bind-api"; bundle-version="2.3.2"; version="2.3.2"; uses:="javax.xml.bind.annotation.adapters,javax.xml.bind.attachment,javax.xml.namespace,javax.xml.stream,javax.xml.transform,javax.xml.validation,org.w3c.dom,org.xml.sax"
                            jakarta.xml.bind-api [38]
                              Unresolved requirement: Import-Package: javax.activation
                       Unresolved requirement: Import-Package: javax.xml.bind.annotation; version="[2.3.0,3.0.0)"
                         -> Export-Package: javax.xml.bind.annotation; bundle-symbolic-name="jakarta.xml.bind-api"; bundle-version="2.3.2"; version="2.3.2"; uses:="javax.xml.bind,javax.xml.parsers,javax.xml.transform,javax.xml.transform.dom,org.w3c.dom"
         Unresolved requirement: Require-Bundle: com.fasterxml.jackson.module.jackson-module-jaxb-annotations; bundle-version="2.10.1"
           -> Bundle-SymbolicName: com.fasterxml.jackson.module.jackson-module-jaxb-annotations; bundle-version="2.11.0"

	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1844)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1837)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1778)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1742)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY io.janusproject.plugin 4 0 2021-03-01 11:54:38.670
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: io.janusproject.plugin [25]
  Unresolved requirement: Require-Bundle: com.fasterxml.jackson.dataformat.jackson-dataformat-xml; bundle-version="2.10.1"
    -> Bundle-SymbolicName: com.fasterxml.jackson.dataformat.jackson-dataformat-xml; bundle-version="2.11.0"
       com.fasterxml.jackson.dataformat.jackson-dataformat-xml [7]
         Unresolved requirement: Import-Package: com.fasterxml.jackson.module.jaxb; version="[2.11.0,3.0.0)"
           -> Export-Package: com.fasterxml.jackson.module.jaxb; bundle-symbolic-name="com.fasterxml.jackson.module.jackson-module-jaxb-annotations"; bundle-version="2.11.0"; version="2.11.0"; uses:="com.fasterxml.jackson.annotation,com.fasterxml.jackson.core,com.fasterxml.jackson.databind,com.fasterxml.jackson.databind.cfg,com.fasterxml.jackson.databind.introspect,com.fasterxml.jackson.databind.jsontype,com.fasterxml.jackson.databind.type,com.fasterxml.jackson.databind.util,javax.xml.bind.annotation,javax.xml.bind.annotation.adapters"
              com.fasterxml.jackson.module.jackson-module-jaxb-annotations [9]
                Unresolved requirement: Import-Package: javax.activation; version="[1.2.0,2.0.0)"; resolution:="optional"
                Unresolved requirement: Import-Package: javax.xml.bind; version="[2.3.0,3.0.0)"
                  -> Export-Package: javax.xml.bind; bundle-symbolic-name="jakarta.xml.bind-api"; bundle-version="2.3.2"; version="2.3.2"; uses:="javax.xml.bind.annotation.adapters,javax.xml.bind.attachment,javax.xml.namespace,javax.xml.stream,javax.xml.transform,javax.xml.validation,org.w3c.dom,org.xml.sax"
                     jakarta.xml.bind-api [38]
                       Unresolved requirement: Import-Package: javax.activation
                Unresolved requirement: Import-Package: javax.xml.bind.annotation; version="[2.3.0,3.0.0)"
                  -> Export-Package: javax.xml.bind.annotation; bundle-symbolic-name="jakarta.xml.bind-api"; bundle-version="2.3.2"; version="2.3.2"; uses:="javax.xml.bind,javax.xml.parsers,javax.xml.transform,javax.xml.transform.dom,org.w3c.dom"
  Unresolved requirement: Require-Bundle: com.fasterxml.jackson.module.jackson-module-jaxb-annotations; bundle-version="2.10.1"
    -> Bundle-SymbolicName: com.fasterxml.jackson.module.jackson-module-jaxb-annotations; bundle-version="2.11.0"

	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1844)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1837)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1778)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1742)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

**Comment by gallandarakhneorg** [comment]
This issue is a duplicate of #1012.

It is solved for version 0.12.
