### ISSUE TITLE
Error when launching from maven execution plugin

### ISSUE THREAD

**Issue by nmontesg** [sarl/sarl#1093]
Hi,

I am starting to use SARL from visual studio code using maven. I have been following the introduction tutorial to create a "helloworld" project. I have been able to package the application as a jar file, however when launching from the maven execution plugin I get the following error:

```
[INFO] --- exec-maven-plugin:3.1.0:exec (default-cli) @ demo ---
oct 07, 2022 1:55:13 P. M. io.sarl.sre.boot.SreMain runSRE
GRAVE: Cannot create the universe context: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.util.logging.Level.name accessible: module java.logging does not "opens java.util.logging" to unnamed module @594c619b
  at io.sarl.sre.boot.configs.SreConfigModule.provideSreConfig(Unknown Source)
  while locating io.sarl.sre.boot.configs.SreConfig

1 error [io.sarl.sre.IssueCodes.universe_creation]
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.util.logging.Level.name accessible: module java.logging does not "opens java.util.logging" to unnamed module @594c619b
  at io.sarl.sre.boot.configs.SreConfigModule.provideSreConfig(Unknown Source)
  while locating io.sarl.sre.boot.configs.SreConfig

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097)
        at io.sarl.sre.boot.commands.AbstractRunCommand.getSREBootstrap(AbstractRunCommand.java:158)
        at io.sarl.sre.boot.commands.RunSingleAgentCommand.run(RunSingleAgentCommand.java:91)
        at io.bootique.run.DefaultRunner.run(DefaultRunner.java:43)
        at io.bootique.BQRuntime.run(BQRuntime.java:85)
        at io.sarl.sre.boot.SreMain.runSRE(SreMain.java:319)
        at io.sarl.sre.boot.Boot.main(Boot.java:72)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.util.logging.Level.name accessible: module java.logging does not "opens java.util.logging" to unnamed module @594c619b
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at com.fasterxml.jackson.databind.util.ClassUtil.checkAndFixAccess(ClassUtil.java:939)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.fixAccess(FieldProperty.java:104)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder._fixAccess(BeanDeserializerBuilder.java:484)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder.build(BeanDeserializerBuilder.java:350)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:252)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:466)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:466)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:466)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4389)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4168)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2467)
        at io.bootique.config.jackson.JsonNodeConfigurationFactory.config(JsonNodeConfigurationFactory.java:57)
        at io.sarl.sre.boot.configs.SreConfig.getConfiguration(SreConfig.java:100)
        at io.sarl.sre.boot.configs.SreConfigModule.provideSreConfig(SreConfigModule.java:77)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:286)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094)
        ... 6 more
```

I am using the following properties in my pom.xml file:

```
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
    <sarl.version>0.12.0</sarl.version>
	  <jdk.version>1.8</jdk.version>
    <janus.version>3.0.12.0</janus.version>
  </properties>
```

I am running a Linux 64bits machine with openJDK 17.0.4

I enjoy agent-oriented programming and are interested in getting my feet wet with SARL, so any help would be greatly appreciated.

As a side note, it would be nice to have a VScode extension for syntax highlighting and/or completion of .sarl files, just a suggestion for future features.

**Comment by gallandarakhneorg** [comment]
Thank you for your report.

The error indicates that your Java virtual machine does not allow to call "Field.setAccessible()". It may be due to a specific version of your VM. You're using the JVM 17. At this time SARL is working onyl on JVM 8 and 11. There is no warranty regarding the use of recent JVM.

Please downgrade our JVM version to 11.

Regarding the VScode extension, unfortunately, these is no man power in our development teams for working on this feature. This contribution must be written by some open-source developper that is not known at this time.

**Comment by gallandarakhneorg** [comment]
We are currently working on the adaption of the code for the version 11 of Java (see Issue #955).
Support for recent JVM will be applied later.
