### ISSUE TITLE
Eclipse error on the editor state.

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1115]
The following error message appears in Eclipse SARL:
```
Error updating dirty state editor
Cannot use getURI if this dirty resource is not connected to a document
```
The error in the Eclipse log is:
```
!ENTRY org.eclipse.xtext.ui 4 0 2023-09-12 14:40:56.699
!MESSAGE Error updating dirty state editor
!STACK 0
java.lang.IllegalStateException: Cannot use getURI if this dirty resource is not connected to a document
	at org.eclipse.xtext.ui.editor.DocumentBasedDirtyResource.getURI(DocumentBasedDirtyResource.java:126)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$ClientAwareDirtyResource.getURI(DirtyStateEditorSupport.java:299)
	at org.eclipse.xtext.ui.editor.DirtyStateManager$1.getUri(DirtyStateManager.java:90)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$UpdateEditorStateJob.mergePendingDeltas(DirtyStateEditorSupport.java:116)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$UpdateEditorStateJob.run(DirtyStateEditorSupport.java:146)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.xtext.ui 4 0 2023-09-12 14:40:56.699
!MESSAGE Error updating dirty state editor
!STACK 0
java.lang.IllegalStateException: Cannot use getURI if this dirty resource is not connected to a document
	at org.eclipse.xtext.ui.editor.DocumentBasedDirtyResource.getURI(DocumentBasedDirtyResource.java:126)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$ClientAwareDirtyResource.getURI(DirtyStateEditorSupport.java:299)
	at org.eclipse.xtext.ui.editor.DirtyStateManager$1.getUri(DirtyStateManager.java:90)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$UpdateEditorStateJob.mergePendingDeltas(DirtyStateEditorSupport.java:116)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$UpdateEditorStateJob.run(DirtyStateEditorSupport.java:146)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.xtext.ui 4 0 2023-09-12 14:41:01.110
!MESSAGE Error updating dirty state editor
!STACK 0
java.lang.IllegalStateException: Cannot use getURI if this dirty resource is not connected to a document
	at org.eclipse.xtext.ui.editor.DocumentBasedDirtyResource.getURI(DocumentBasedDirtyResource.java:126)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$ClientAwareDirtyResource.getURI(DirtyStateEditorSupport.java:299)
	at org.eclipse.xtext.ui.editor.DirtyStateManager$1.getUri(DirtyStateManager.java:90)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$UpdateEditorStateJob.mergePendingDeltas(DirtyStateEditorSupport.java:116)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$UpdateEditorStateJob.run(DirtyStateEditorSupport.java:146)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by gallandarakhneorg** [comment]
Info: https://github.com/eclipse/xtext-eclipse/issues/1139
