### ISSUE TITLE
Cannot create Skill implementing a capacity with a generic type

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1135]
Let the following capacity definition :

```sarl
capacity C {
    def getData(name : String, type : Class<T>) : T with T
    def setData(name : String, type : Class<T>, value : T) with T
    def isDefined(name : String) : boolean
}
```

When the wizard tool for creating a skill is used, the capacity `C` is added as implemented capacity for the skill to be created.

The wizard tool cannot create the skill because of the error: `Unknown generic type T`.

**Comment by gallandarakhneorg** [comment]
This error comes from the SARL compiler's construct builder:

```
java.lang.TypeNotPresentException: Type T not present
	at io.sarl.lang.codebuilder.builders.ExpressionBuilderImpl.parseType(ExpressionBuilderImpl.java:149)
	at io.sarl.lang.codebuilder.builders.AbstractBuilder.newTypeRef(AbstractBuilder.java:197)
	at io.sarl.lang.codebuilder.builders.SarlActionBuilderImpl.setReturnType(SarlActionBuilderImpl.java:151)
	at io.sarl.eclipse.util.Jdt2Ecore.createActionsWith(Jdt2Ecore.java:538)
```

I have added the "Language & compiler" tag to the issue.
