### ISSUE TITLE
Janus test fails on agent kill

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1155]
The following exception is thrown during Janus network tests:

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.902 s <<< FAILURE! -- in run: Bug #546 - Agent kill
Error:  io.sarl.sre.janus.itests.bugs.to1000.bug546.AgentKillIT.launchTest(SreRunContext) -- Time elapsed: 0.893 s <<< ERROR!
java.lang.RuntimeException: io.sarl.lang.core.OwnerNotFoundException
	at io.sarl.sre.test.framework.context.SreRunContextImpl.waitForTheKernel(SreRunContextImpl.java:560)
	at io.sarl.sre.test.framework.context.SreRunContextImpl.waitForTheKernel(SreRunContextImpl.java:525)
	at io.sarl.sre.test.framework.context.SreRunContextImpl.runSre(SreRunContextImpl.java:296)
	at io.sarl.sre.test.framework.context.SreRunContext.runSre(SreRunContext.java:888)
	at io.sarl.sre.janus.itests.bugs.to1000.bug546.AgentKillIT.launchTest(AgentKillIT.java:61)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.sarl.sre.test.framework.extension.SreRunExtension.interceptTestMethod(SreRunExtension.java:87)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: io.sarl.lang.core.OwnerNotFoundException
		at io.sarl.lang.core.AgentTrait.$getSkill(AgentTrait.java:122)
		at io.sarl.lang.core.AgentTrait.getSkill(AgentTrait.java:95)
		at io.sarl.sre.janus.skills.internal.InternalEventBusSkill.lambda$new$0(InternalEventBusSkill.java:183)
		at io.sarl.sre.janus.skills.internal.EventBus.getExecutor(EventBus.java:124)
		at io.sarl.sre.janus.skills.internal.EventBus.asyncDispatch(EventBus.java:381)
		at io.sarl.sre.janus.skills.internal.InternalEventBusSkill.fireEvent(InternalEventBusSkill.java:389)
		at io.sarl.sre.janus.skills.internal.InternalEventBusSkill$ExternalEventBusAccessor.receiveEvent(InternalEventBusSkill.java:109)
		at io.sarl.sre.janus.spaces.AbstractEventSpace.emitLocally(AbstractEventSpace.java:401)
		at io.sarl.sre.janus.spaces.AbstractEventSpace.emit(AbstractEventSpace.java:302)
		at io.sarl.sre.janus.internal.SpaceParticipantEventEmitter.participantLeft(SpaceParticipantEventEmitter.java:146)
		at io.sarl.sre.janus.spaces.AbstractEventSpace.unregisterFromSpace(AbstractEventSpace.java:248)
		at io.sarl.sre.janus.spaces.OpenLocalEventSpace.unregister(OpenLocalEventSpace.java:69)
		at io.sarl.sre.janus.services.lifecycle.AgentLife.detachAgentFromPlatform(AgentLife.java:390)
		at io.sarl.sre.janus.services.lifecycle.AgentLife.stop(AgentLife.java:489)
		at io.sarl.sre.janus.services.lifecycle.AgentLife.stop(AgentLife.java:988)
		at io.sarl.sre.janus.services.lifecycle.AbstractLifecycleService.killAgent(AbstractLifecycleService.java:753)
		at io.sarl.sre.janus.skills.bic.LifecycleSkill.lambda$killMe$1(LifecycleSkill.java:97)
		at io.sarl.sre.janus.services.executor.tasks.SreRunnable.internalRun(SreRunnable.java:102)
		at io.sarl.sre.janus.services.executor.tasks.SreRunnable.run(SreRunnable.java:111)
		at io.sarl.sre.janus.services.executor.tasks.EarlyExitException.runPostTreatment(EarlyExitException.java:63)
		at io.sarl.sre.janus.services.executor.tasks.SreRunnable.run(SreRunnable.java:115)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.sarl.lang.core.OwnerNotFoundException
	at io.sarl.lang.core.AgentTrait.$getSkill(AgentTrait.java:122)
	at io.sarl.lang.core.AgentTrait.getSkill(AgentTrait.java:95)
	at io.sarl.sre.janus.skills.internal.InternalEventBusSkill.lambda$new$0(InternalEventBusSkill.java:183)
	at io.sarl.sre.janus.skills.internal.EventBus.getExecutor(EventBus.java:124)
	at io.sarl.sre.janus.skills.internal.EventBus.asyncDispatch(EventBus.java:381)
	at io.sarl.sre.janus.skills.internal.InternalEventBusSkill.fireEvent(InternalEventBusSkill.java:389)
	at io.sarl.sre.janus.skills.internal.InternalEventBusSkill$ExternalEventBusAccessor.receiveEvent(InternalEventBusSkill.java:109)
	at io.sarl.sre.janus.spaces.AbstractEventSpace.emitLocally(AbstractEventSpace.java:401)
	at io.sarl.sre.janus.spaces.AbstractEventSpace.emit(AbstractEventSpace.java:302)
	at io.sarl.sre.janus.internal.SpaceParticipantEventEmitter.participantLeft(SpaceParticipantEventEmitter.java:146)
	at io.sarl.sre.janus.spaces.AbstractEventSpace.unregisterFromSpace(AbstractEventSpace.java:248)
	at io.sarl.sre.janus.spaces.OpenLocalEventSpace.unregister(OpenLocalEventSpace.java:69)
	at io.sarl.sre.janus.services.lifecycle.AgentLife.detachAgentFromPlatform(AgentLife.java:390)
	at io.sarl.sre.janus.services.lifecycle.AgentLife.stop(AgentLife.java:489)
	at io.sarl.sre.janus.services.lifecycle.AgentLife.stop(AgentLife.java:988)
	at io.sarl.sre.janus.services.lifecycle.AbstractLifecycleService.killAgent(AbstractLifecycleService.java:753)
	at io.sarl.sre.janus.skills.bic.LifecycleSkill.lambda$killMe$1(LifecycleSkill.java:97)
	at io.sarl.sre.janus.services.executor.tasks.SreRunnable.internalRun(SreRunnable.java:102)
	at io.sarl.sre.janus.services.executor.tasks.SreRunnable.run(SreRunnable.java:111)
	at io.sarl.sre.janus.services.executor.tasks.EarlyExitException.runPostTreatment(EarlyExitException.java:63)
	at io.sarl.sre.janus.services.executor.tasks.SreRunnable.run(SreRunnable.java:115)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at io.sarl.sre.janus.services.executor.policies.AbstractThreadExecutorPolicy.runRejectedTask(AbstractThreadExecutorPolicy.java:65)
	at io.sarl.sre.janus.services.executor.policies.AbstractThreadExecutorPolicy.rejectedExecution(AbstractThreadExecutorPolicy.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
	at io.sarl.sre.janus.services.executor.jreservice.JreExecutorService.executeAsap(JreExecutorService.java:409)
	at io.sarl.sre.janus.skills.bic.SchedulesSkill.executeAsap(SchedulesSkill.java:1102)
	at io.sarl.sre.janus.skills.internal.EventBus.executeAsynchronouslyBehaviorMethods(EventBus.java:524)
	at io.sarl.sre.janus.skills.internal.EventBus$2.internalRun(EventBus.java:371)
	at io.sarl.sre.janus.services.executor.tasks.SreRunnable.run(SreRunnable.java:111)
	at io.sarl.sre.janus.skills.bic.SchedulesSkill.lambda$executeAsap$1(SchedulesSkill.java:1095)
	at io.sarl.sre.janus.skills.bic.SchedulesSkill$TaskRunner.coreRun(SchedulesSkill.java:411)
	at io.sarl.sre.janus.skills.bic.SchedulesSkill$TaskRunner.internalRun(SchedulesSkill.java:452)
	at io.sarl.sre.janus.services.executor.tasks.SreRunnable.run(SreRunnable.java:111)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by gallandarakhneorg** [comment]
Cannot reproduce this issue.
