### ISSUE TITLE
IllegalArgumentException in the JVM model inferrer

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#282]
The following error occurs in a Maven-based SARL project:

```
java.lang.IllegalArgumentException: The type io.sarl.lang.annotation.DefaultValueUse is not on the classpath.
	at org.eclipse.xtext.xbase.jvmmodel.JvmAnnotationReferenceBuilder.annotationRef(JvmAnnotationReferenceBuilder.java:83)
	at org.eclipse.xtext.xbase.jvmmodel.JvmAnnotationReferenceBuilder.annotationRef(JvmAnnotationReferenceBuilder.java:60)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer$11.apply(SARLJvmModelInferrer.java:1061)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer$11.apply(SARLJvmModelInferrer.java:1)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.initializeSafely(JvmTypesBuilder.java:204)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.toMethod(JvmTypesBuilder.java:667)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.generateAction(SARLJvmModelInferrer.java:1036)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.generateCodeForFeatures(SARLJvmModelInferrer.java:382)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer$SkillGenerator.generate(SARLJvmModelInferrer.java:1656)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer$AbstractGenerator.apply(SARLJvmModelInferrer.java:1403)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer$AbstractGenerator.apply(SARLJvmModelInferrer.java:1)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:365)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:159)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.postParse(XtextDocumentReconcileStrategy.java:169)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:146)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:65)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:413)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:393)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$DocumentListener$1.exec(XtextReconciler.java:124)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$DocumentListener$1.exec(XtextReconciler.java:1)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:418)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.process(XtextDocument.java:328)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$DocumentListener.performNecessaryUpdates(XtextReconciler.java:122)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.updateContentBeforeRead(XtextDocument.java:214)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:486)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:465)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:105)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:82)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:65)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by gallandarakhneorg** [comment]
The project definition in  Eclipse seems to be invalid (too old).
For solving this problem, you should delete the project and recreate it.
