### ISSUE TITLE
Windows 10 Problem launching SARL client

### ISSUE THREAD

**Issue by m-irigoyen** [sarl/sarl#324]
Confugration:
* Windows 10 latest version at the time (16/10/2015)
* Java 8
* SARL 1.0 (downloaded a few minutes ago on http://www.sarl.io/download/index.html )
* Janus : io.janusproject.kernel-2.1.0.0-20151016.050340-218-with-dependencies

I unzip the sarl eclipse client, launch it : after a few seconds i get a crash report.

Here's the log found in /configuration :
```
!SESSION 2015-10-16 16:46:32.656 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.update.configurator 4 0 2015-10-16 16:46:41.417
!MESSAGE Could not install bundle plugins/com.google.guava_15.0.0.v201403281430.jar   A bundle is already installed with the name "com.google.guava" and version "15.0.0.v201403281430"

[... LOG FILE CUT BY SARL DEVELOPER ...]

!ENTRY org.eclipse.update.configurator 4 0 2015-10-16 16:46:45.562
!MESSAGE Could not install bundle plugins/org.w3c.dom.svg_1.1.0.v201011041433.jar   A bundle is already installed with the name "org.w3c.dom.svg" and version "1.1.0.v201011041433"

!ENTRY org.eclipse.osgi 4 0 2015-10-16 16:46:47.025
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: Cannot load 64-bit SWT libraries on 32-bit JVM
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:256)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:236)
	at org.eclipse.swt.internal.C.<clinit>(C.java:21)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:138)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:716)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:162)
	at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:165)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:107)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by gallandarakhneorg** [comment]
The last message indicates 'Cannot load 64-bit SWT libraries on 32-bit JVM'.

It means that the Java 8 virtual machine that is used for running the SARL Eclipse product is a 32-bit version, not a 64-bit version.

Please check your Java configuration, and the version of Java on the command line with:
```
java -version
```

You could also specify the VM that must be used for launching the Eclipse product. In the file `eclipse.ini`, add the command-line option:
```
-vm C:\Program Files\Java\jre8\bin\javaw
```

Thank you for giving you feedback.
