### ISSUE TITLE
Exceptions when agent has no name.

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#356]
When typing the following code (it may occurs when entering the code by hand), and the SARL tools generates a couple of exceptions:
```
agent 
```

Exception 1:
```
0    [main] ERROR org.eclipse.xtext.xbase.resource.BatchLinkableResource  - resolution of uriFragment '|0' failed.
java.lang.IllegalArgumentException: Qualified name cannot be null
	at org.eclipse.xtext.naming.IQualifiedNameConverter$DefaultImpl.toQualifiedName(IQualifiedNameConverter.java:57)
	at org.eclipse.xtext.xbase.XbaseQualifiedNameConverter.toQualifiedName(XbaseQualifiedNameConverter.java:36)
	at org.eclipse.xtend.core.scoping.XtendImportedNamespaceScopeProvider.doGetAllDescriptions(XtendImportedNamespaceScopeProvider.java:361)
	at org.eclipse.xtend.core.scoping.XtendImportedNamespaceScopeProvider.internalGetAllDescriptions(XtendImportedNamespaceScopeProvider.java:354)
	at org.eclipse.xtext.xbase.scoping.XImportSectionNamespaceScopeProvider$2.get(XImportSectionNamespaceScopeProvider.java:274)
	at org.eclipse.xtext.xbase.scoping.XImportSectionNamespaceScopeProvider$2.get(XImportSectionNamespaceScopeProvider.java:1)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtext.xbase.scoping.XImportSectionNamespaceScopeProvider.getAllDescriptions(XImportSectionNamespaceScopeProvider.java:271)
	at org.eclipse.xtend.core.scoping.XtendImportedNamespaceScopeProvider.getScope(XtendImportedNamespaceScopeProvider.java:114)
	at org.eclipse.xtext.xbase.scoping.batch.TypeScopes.createTypeScope(TypeScopes.java:59)
	at org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider.getScope(XbaseBatchScopeProvider.java:105)
	at org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider.getScope(XbaseWithAnnotationsBatchScopeProvider.java:53)
[...]
```

Exception 2:
```
10   [main] ERROR org.eclipse.xtext.xbase.resource.BatchLinkableResource  - resolution of uriFragment '|0' failed.
java.lang.IllegalArgumentException: Qualified name cannot be null
	at org.eclipse.xtext.naming.IQualifiedNameConverter$DefaultImpl.toQualifiedName(IQualifiedNameConverter.java:57)
	at org.eclipse.xtext.xbase.XbaseQualifiedNameConverter.toQualifiedName(XbaseQualifiedNameConverter.java:36)
	at org.eclipse.xtend.core.scoping.XtendImportedNamespaceScopeProvider.doGetAllDescriptions(XtendImportedNamespaceScopeProvider.java:361)
	at org.eclipse.xtend.core.scoping.XtendImportedNamespaceScopeProvider.internalGetAllDescriptions(XtendImportedNamespaceScopeProvider.java:354)
	at org.eclipse.xtext.xbase.scoping.XImportSectionNamespaceScopeProvider$2.get(XImportSectionNamespaceScopeProvider.java:274)
	at org.eclipse.xtext.xbase.scoping.XImportSectionNamespaceScopeProvider$2.get(XImportSectionNamespaceScopeProvider.java:1)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtext.xbase.scoping.XImportSectionNamespaceScopeProvider.getAllDescriptions(XImportSectionNamespaceScopeProvider.java:271)
	at org.eclipse.xtend.core.scoping.XtendImportedNamespaceScopeProvider.getScope(XtendImportedNamespaceScopeProvider.java:114)
	at org.eclipse.xtext.xbase.scoping.batch.TypeScopes.createTypeScope(TypeScopes.java:59)
	at org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider.getScope(XbaseBatchScopeProvider.java:105)
	at org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider.getScope(XbaseWithAnnotationsBatchScopeProvider.java:53)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getScope(DefaultLinkingService.java:59)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getLinkedObjects(DefaultLinkingService.java:119)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:250)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:119)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:203)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)
	at org.eclipse.xtext.xtype.impl.XImportDeclarationImpl.getImportedType(XImportDeclarationImpl.java:253)
	at org.eclipse.xtend.core.scoping.XtendImportedNamespaceScopeProvider.getImportScope(XtendImportedNamespaceScopeProvider.java:280)
	at org.eclipse.xtend.core.scoping.XtendImportedNamespaceScopeProvider.access$2(XtendImportedNamespaceScopeProvider.java:250)
[...]
```

Exception 3:
```
16   [main] ERROR org.eclipse.xtext.xbase.resource.BatchLinkableResource  - resolution of uriFragment '|1' failed.
java.lang.NullPointerException
	at org.eclipse.xtext.util.Strings.split(Strings.java:359)
	at org.eclipse.xtend.core.scoping.KnownTypesScope.getExactMatch(KnownTypesScope.java:80)
	at org.eclipse.xtend.core.scoping.KnownTypesScope.doGetSingleElement(KnownTypesScope.java:48)
	at org.eclipse.xtend.core.scoping.AbstractKnownTypesScope.doGetSingleElement(AbstractKnownTypesScope.java:65)
	at org.eclipse.xtend.core.scoping.AbstractKnownTypesScope.getSingleElement(AbstractKnownTypesScope.java:38)
	at org.eclipse.xtend.core.scoping.PrimitiveAwareScope.getSingleElement(PrimitiveAwareScope.java:39)
	at org.eclipse.xtend.core.scoping.CachingTypeScope.getSingleElement(CachingTypeScope.java:40)
	at org.eclipse.xtend.core.scoping.AbstractKnownTypesScope.getSingleElement(AbstractKnownTypesScope.java:42)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getLinkedObjects(DefaultLinkingService.java:121)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:250)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:119)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:199)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)
	at org.eclipse.xtext.common.types.impl.JvmTypeReferenceImplCustom.eResolveProxy(JvmTypeReferenceImplCustom.java:37)
	at org.eclipse.xtext.common.types.impl.JvmParameterizedTypeReferenceImpl.getType(JvmParameterizedTypeReferenceImpl.java:111)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.transform(SARLJvmModelInferrer.java:1369)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.transform(SARLJvmModelInferrer.java:770)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.appendSarlMembers(SARLJvmModelInferrer.java:1505)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.initialize(SARLJvmModelInferrer.java:424)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer$1.run(SARLJvmModelInferrer.java:284)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer$3.run(XtendJvmModelInferrer.java:211)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.ensureJvmMembersInitialized(BatchLinkableResource.java:231)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.getOrInstall(JvmModelAssociator.java:112)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.getLogicalContainerMapping(JvmModelAssociator.java:127)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.getAssociatedExpression(JvmModelAssociator.java:134)
	at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareReentrantTypeResolver.recordExpressions(LogicalContainerAwareReentrantTypeResolver.java:407)
[...]
```

Exception 4:
```
18   [main] ERROR org.eclipse.xtext.xbase.resource.BatchLinkableResource  - resolution of uriFragment '|1' failed.
java.lang.NullPointerException
	at org.eclipse.xtext.util.Strings.split(Strings.java:359)
	at org.eclipse.xtend.core.scoping.KnownTypesScope.getExactMatch(KnownTypesScope.java:80)
	at org.eclipse.xtend.core.scoping.KnownTypesScope.doGetSingleElement(KnownTypesScope.java:48)
	at org.eclipse.xtend.core.scoping.AbstractKnownTypesScope.doGetSingleElement(AbstractKnownTypesScope.java:65)
	at org.eclipse.xtend.core.scoping.AbstractKnownTypesScope.getSingleElement(AbstractKnownTypesScope.java:38)
	at org.eclipse.xtend.core.scoping.PrimitiveAwareScope.getSingleElement(PrimitiveAwareScope.java:39)
	at org.eclipse.xtend.core.scoping.CachingTypeScope.getSingleElement(CachingTypeScope.java:40)
	at org.eclipse.xtend.core.scoping.AbstractKnownTypesScope.getSingleElement(AbstractKnownTypesScope.java:42)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getLinkedObjects(DefaultLinkingService.java:121)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:250)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:119)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:203)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)
	at org.eclipse.xtext.common.types.impl.JvmTypeReferenceImplCustom.eResolveProxy(JvmTypeReferenceImplCustom.java:37)
	at org.eclipse.xtext.common.types.impl.JvmParameterizedTypeReferenceImpl.getType(JvmParameterizedTypeReferenceImpl.java:111)
[...]
```

**Comment by gallandarakhneorg** [comment]
A part of the problem must be fixed in the Xtend API. See the [issue 482758](https://bugs.eclipse.org/bugs/show_bug.cgi?id=482758).

**Comment by gallandarakhneorg** [comment]
The provided part is temporary since a part of the Xtend API cannot be patched with object extension.
This issue stays open until the Xtend issue is fixed.

**Comment by gallandarakhneorg** [comment]
Another exception is thrown when no type name is provided:
```
java.lang.IllegalArgumentException: Qualified name cannot be null
	at org.eclipse.xtext.naming.IQualifiedNameConverter$DefaultImpl.toQualifiedName(IQualifiedNameConverter.java:57)
	at org.eclipse.xtext.xbase.XbaseQualifiedNameConverter.toQualifiedName(XbaseQualifiedNameConverter.java:36)
	at org.eclipse.xtend.core.resource.XtendResourceDescription$4.apply(XtendResourceDescription.java:174)
	at org.eclipse.xtend.core.resource.XtendResourceDescription$4.apply(XtendResourceDescription.java:1)
	at org.eclipse.xtend.core.resource.XtendResourceDescription.registerAllTypes(XtendResourceDescription.java:205)
	at org.eclipse.xtend.core.resource.XtendResourceDescription.getImportedNames(XtendResourceDescription.java:179)
	at org.eclipse.xtext.resource.persistence.SerializableResourceDescription$1.apply(SerializableResourceDescription.java:73)
	at org.eclipse.xtext.resource.persistence.SerializableResourceDescription$1.apply(SerializableResourceDescription.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.eclipse.xtext.resource.persistence.SerializableResourceDescription.createCopy(SerializableResourceDescription.java:78)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable.writeResourceDescription(ResourceStorageWritable.java:138)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable.writeEntries(ResourceStorageWritable.java:76)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResourceStorageWritable.writeEntries(BatchLinkableResourceStorageWritable.java:55)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable.writeResource(ResourceStorageWritable.java:53)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.announceDirtyState(DirtyStateEditorSupport.java:555)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.postParse(XtextDocumentReconcileStrategy.java:179)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:153)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:67)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:442)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:422)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:363)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:98)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:428)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:162)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:360)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by gallandarakhneorg** [comment]
Related discussion in the Xtext community: https://www.eclipse.org/forums/index.php/t/1079616/
