### ISSUE TITLE
java.lang.IllegalArgumentException: The type io.sarl.lang.annotation.SarlSourceCode is not on the classpath.

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#363]
After importing a Maven/SARL project (jaak's trafficsim branch), 15 occurrences of the following exception occur:

```
0    [Worker-3] ERROR org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder  - Error initializing JvmElement
java.lang.IllegalArgumentException: The type io.sarl.lang.annotation.SarlSourceCode is not on the classpath.
	at org.eclipse.xtext.xbase.jvmmodel.JvmAnnotationReferenceBuilder.annotationRef(JvmAnnotationReferenceBuilder.java:83)
	at org.eclipse.xtext.xbase.jvmmodel.JvmAnnotationReferenceBuilder.annotationRef(JvmAnnotationReferenceBuilder.java:60)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.appendGeneratedAnnotation(SARLJvmModelInferrer.java:1827)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer$17.apply(SARLJvmModelInferrer.java:2024)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer$17.apply(SARLJvmModelInferrer.java:1)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.initializeSafely(JvmTypesBuilder.java:206)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.toField(JvmTypesBuilder.java:588)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.translateSarlFormalParameters(SARLJvmModelInferrer.java:2008)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.transform(SARLJvmModelInferrer.java:1023)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer.transform(XtendJvmModelInferrer.java:556)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.transform(SARLJvmModelInferrer.java:829)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.appendSarlMembers(SARLJvmModelInferrer.java:1553)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.initialize(SARLJvmModelInferrer.java:807)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer$5.run(SARLJvmModelInferrer.java:337)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer$3.run(XtendJvmModelInferrer.java:211)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.ensureJvmMembersInitialized(BatchLinkableResource.java:231)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.getOrInstall(JvmModelAssociator.java:112)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.getLogicalContainerMapping(JvmModelAssociator.java:127)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.getAssociatedExpression(JvmModelAssociator.java:134)
	at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareReentrantTypeResolver.recordExpressions(LogicalContainerAwareReentrantTypeResolver.java:407)
	at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareReentrantTypeResolver.prepare(LogicalContainerAwareReentrantTypeResolver.java:401)
	at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareReentrantTypeResolver.computeTypes(LogicalContainerAwareReentrantTypeResolver.java:689)
	at org.eclipse.xtend.core.typesystem.XtendReentrantTypeResolver.computeTypes(XtendReentrantTypeResolver.java:358)
	at org.eclipse.xtext.xbase.typesystem.internal.DefaultReentrantTypeResolver.resolve(DefaultReentrantTypeResolver.java:165)
	at org.eclipse.xtext.xbase.typesystem.internal.DefaultReentrantTypeResolver.reentrantResolve(DefaultReentrantTypeResolver.java:140)
	at org.eclipse.xtext.xbase.typesystem.internal.CompoundReentrantTypeResolver.reentrantResolve(CompoundReentrantTypeResolver.java:79)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$LazyResolvedTypes.resolveTypes(CachingBatchTypeResolver.java:80)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$2.process(CachingBatchTypeResolver.java:57)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$2.process(CachingBatchTypeResolver.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
	at org.eclipse.xtext.util.OnChangeEvictingCache.execWithoutCacheClear(OnChangeEvictingCache.java:129)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver.doResolveTypes(CachingBatchTypeResolver.java:53)
	at org.eclipse.xtext.xbase.typesystem.internal.AbstractBatchTypeResolver.resolveTypes(AbstractBatchTypeResolver.java:69)
	at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:71)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.resolveLazyCrossReferences(BatchLinkableResource.java:165)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:528)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:234)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:115)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:248)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:280)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:117)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by gallandarakhneorg** [comment]
The compiler project was configured for using SARL `1.0.0-SNAPSHOT`.
After changing the project's configuration for using SARL `0.3.0-SNAPSHOT` (the same version as the Eclipse product), the exceptions do not occur any more.

The problem is that the JVM inferrer fails, and perhaps before the output of an error related to the invalid version.

**Comment by gallandarakhneorg** [comment]
Two new issues are added in the SARL validator:
* SARL library `io.sarl.lang.core` not found on the project's classpath.
* The version of the SARL library given by the class `SARLVersion` is not compatible with the compiler.
