### ISSUE TITLE
Auto-completion does not work

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#406]
Auto-completion does not work on members of Java or SARL objects.

For example, the following code cannot give me an auto-completion popup:
```
Math.
```

**Comment by gallandarakhneorg** [comment]
The error log given by the product for the use case is:
```
1    [main] ERROR org.eclipse.xtext.ui.editor.contentassist.antlr.ParserBasedContentAssistContextFactory  - java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.ParserBasedContentAssistContextFactory$StatefulFactory.doCreateContexts(ParserBasedContentAssistContextFactory.java:286)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.ParserBasedContentAssistContextFactory$StatefulFactory.create(ParserBasedContentAssistContextFactory.java:223)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.ParserBasedContentAssistContextFactory.create(ParserBasedContentAssistContextFactory.java:778)
[...]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractPartialContentAssistParser.getFollowElements(AbstractPartialContentAssistParser.java:162)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractPartialContentAssistParser.getFollowElements(AbstractPartialContentAssistParser.java:56)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.ParserBasedContentAssistContextFactory$PartialStatefulFactory.parseFollowElements(ParserBasedContentAssistContextFactory.java:744)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.ParserBasedContentAssistContextFactory$PartialStatefulFactory.createContextsForLastCompleteNode(ParserBasedContentAssistContextFactory.java:739)
[...]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractPartialContentAssistParser.getFollowElements(AbstractPartialContentAssistParser.java:157)
	... 11 more
Caused by: java.lang.IllegalArgumentException: tokenType 44 seems to be invalid.
	at org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser.createLookAheadTerminal(AbstractInternalContentAssistParser.java:533)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser$DefaultFollowElementFactory.createFollowElement(AbstractInternalContentAssistParser.java:76)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser.createFollowElement(AbstractInternalContentAssistParser.java:509)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser$5.announceEof(AbstractInternalContentAssistParser.java:445)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser.announceEof(AbstractInternalContentAssistParser.java:570)
	at org.eclipse.xtext.ui.editor.contentassist.antlr.ObservableXtextTokenStream.LA(ObservableXtextTokenStream.java:48)
	at io.sarl.lang.ui.contentassist.antlr.internal.InternalSARLParser.rule__XMemberFeatureCall__Group__1__Impl(InternalSARLParser.java:8358)
	at io.sarl.lang.ui.contentassist.antlr.internal.InternalSARLParser.rule__XMemberFeatureCall__Group__1(InternalSARLParser.java:8313)
	at io.sarl.lang.ui.contentassist.antlr.internal.InternalSARLParser.rule__XMemberFeatureCall__Group__0(InternalSARLParser.java:8235)
	at io.sarl.lang.ui.contentassist.antlr.internal.InternalSARLParser.ruleXMemberFeatureCall(InternalSARLParser.java:7766)
	at io.sarl.lang.ui.contentassist.antlr.internal.InternalSARLParser.rule__XPostfixOperation__Group__0__Impl(InternalSARLParser.java:7838)
	at io.sarl.lang.ui.contentassist.antlr.internal.InternalSARLParser.rule__XPostfixOperation__Group__0(InternalSARLParser.java:7794)
	at io.sarl.lang.ui.contentassist.antlr.internal.InternalSARLParser.ruleXPostfixOperation(InternalSARLParser.java:7596)
	at io.sarl.lang.ui.contentassist.antlr.internal.InternalSARLParser.rule__XCastedExpression__Group__0__Impl(InternalSARLParser.java:7237)
	at io.sarl.lang.ui.contentassist.antlr.internal.InternalSARLParser.rule__XCastedExpression__Group__0(InternalSARLParser.java:7193)
	at io.sarl.lang.ui.contentassist.antlr.internal.InternalSARLParser.ruleXCastedExpression(InternalSARLParser.java:7511)
[...]
```

**Comment by gallandarakhneorg** [comment]
Solution is discussed on the [Xtext forum](https://www.eclipse.org/forums/index.php/t/1074655/).

Issue submitted to Xtext: [487638](https://bugs.eclipse.org/bugs/show_bug.cgi?id=487638)

**Comment by gallandarakhneorg** [comment]
```
java.lang.ClassCastException: io.sarl.lang.ui.contentassist.SARLProposalProvider cannot be cast to org.eclipse.xtext.ui.editor.contentassist.RepeatedContentAssistProcessor$ModeAware
	at org.eclipse.xtext.ui.editor.contentassist.RepeatedContentAssistProcessor.getModeAwareProposalProvider(RepeatedContentAssistProcessor.java:66)
	at org.eclipse.xtext.ui.editor.contentassist.RepeatedContentAssistProcessor.assistSessionEnded(RepeatedContentAssistProcessor.java:137)
	at org.eclipse.jface.text.contentassist.ContentAssistant.fireSessionEndEvent(ContentAssistant.java:2404)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.hide(CompletionProposalPopup.java:1098)
	at org.eclipse.jface.text.contentassist.ContentAssistant.hide(ContentAssistant.java:2160)
	at org.eclipse.jface.text.contentassist.ContentAssistant.uninstall(ContentAssistant.java:1483)
	at org.eclipse.jface.text.source.SourceViewer.unconfigure(SourceViewer.java:695)
	at org.eclipse.jface.text.source.SourceViewer.handleDispose(SourceViewer.java:741)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.handleDispose(ProjectionViewer.java:1296)
	at org.eclipse.jface.text.TextViewer$2.widgetDisposed(TextViewer.java:1731)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:124)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
```
