### ISSUE TITLE
Cannot create SARL file

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#412]
It is impossible to create a SARL file with the "New SARL file" command.

Creating the file with the standard "New File" with a filename extension equal to ".sarl" works.

**Comment by gallandarakhneorg** [comment]
Exception is:
```

java.lang.NullPointerException
	at io.sarl.eclipse.wizards.newfile.NewSarlFileWizardPage.getInitialContents(NewSarlFileWizardPage.java:95)
	at org.eclipse.ui.dialogs.WizardNewFileCreationPage.createNewFile(WizardNewFileCreationPage.java:380)
	at io.sarl.eclipse.wizards.newfile.NewSarlFileWizard.performFinish(NewSarlFileWizard.java:78)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:790)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:423)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
```
