### ISSUE TITLE
Invalid URL in Javadoc

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#437]
In the SARL product, it is possible to display the documentation of a type by putting the mouse cursor over a type during a couple of second.

This causes an invalid URL format:
```

java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088)
	at org.eclipse.jdt.internal.corext.javadoc.JavaDocLocations.parseURL(JavaDocLocations.java:732)
	at org.eclipse.jdt.internal.corext.javadoc.JavaDocLocations.getLibraryJavadocLocation(JavaDocLocations.java:294)
	at org.eclipse.jdt.internal.corext.javadoc.JavaDocLocations.getJavadocBaseLocation(JavaDocLocations.java:312)
	at org.eclipse.jdt.internal.corext.javadoc.JavaDocLocations.getJavadocLocation(JavaDocLocations.java:451)
	at org.eclipse.jdt.ui.JavaUI.getJavadocLocation(JavaUI.java:994)
	at org.eclipse.jdt.internal.corext.javadoc.JavaDocLocations.getBaseURL(JavaDocLocations.java:630)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getHoverInfo(JavadocHover.java:723)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.internalGetHoverInfo(JavadocHover.java:635)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getHoverInfo2(JavadocHover.java:627)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:164)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:86)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:165)
```

**Comment by gallandarakhneorg** [comment]
The JDT JavaDoc hover is exploring the classpath for retreiving the locations of the Javadoc. One of the included libraries is `io.sarl.lang.core`. When the SARL product is launched inside the Eclipse IDE (for testing), the path to `io.sarl.lang.core` is a local filename. It cannot be parsed as an URI because of the lack of scheme.

I assume this is a bug is the Eclipse JDT module. This issue should never append when the product is started outside the Eclipse IDE.
