### ISSUE TITLE
Quick fix tests have conflicts in formatted regions.

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#443]
When runing the quick fix unit tests, the following error occurs:
```
!ENTRY org.apache.log4j 4 0 2016-07-30 11:34:48.294
!MESSAGE org.eclipse.xtext.util.ExceptionAcceptor  - Conflicting Regions.
{{{}}}: newLine=1 at offset=89 length=0
[[[]]]: newLine=2 at offset=89 length=0
------------------------------- document snippet -------------------------------
package io.sarl.tests.quickfix.org_eclipse_xtend_core_validation_issuecodes_wrong_package{{{}}}[[[]]]
--------------------------------------------------------------------------------

!STACK 0
org.eclipse.xtext.formatting2.internal.ConflictingRegionsException: Conflicting Regions.
{{{}}}: newLine=1 at offset=89 length=0
[[[]]]: newLine=2 at offset=89 length=0
------------------------------- document snippet -------------------------------
package io.sarl.tests.quickfix.org_eclipse_xtend_core_validation_issuecodes_wrong_package{{{}}}[[[]]]
--------------------------------------------------------------------------------
	at org.eclipse.xtext.formatting2.internal.TextSegmentSet.handleConflict(TextSegmentSet.java:66)
	at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.replaceExistingEntry(ArrayListTextSegmentSet.java:131)
	at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.add(ArrayListTextSegmentSet.java:43)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.addReplacer(FormattableDocument.java:73)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.set(FormattableDocument.java:310)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.append(FormattableDocument.java:94)
	at org.eclipse.xtend.core.formatting2.XtendFormatter._format(XtendFormatter.java:154)
	at org.eclipse.xtend.core.formatting2.XtendFormatter.format(XtendFormatter.java:891)
	at io.sarl.lang.formatting2.SARLFormatter.format(SARLFormatter.java:171)
	at org.eclipse.xtext.formatting2.AbstractFormatter2._format(AbstractFormatter2.java:202)
	at org.eclipse.xtend.core.formatting2.XtendFormatter.format(XtendFormatter.java:801)
	at io.sarl.lang.formatting2.SARLFormatter.format(SARLFormatter.java:171)
	at org.eclipse.xtext.formatting2.AbstractFormatter2.format(AbstractFormatter2.java:269)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:161)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:203)
	at org.eclipse.xtext.resource.XtextResource.doSave(XtextResource.java:369)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:1430)
	at io.sarl.lang.ui.tests.quickfix.AbstractSARLQuickfixTest$QuickFixAsserts.assertQuickFix(AbstractSARLQuickfixTest.java:297)
	at io.sarl.lang.ui.tests.quickfix.AbstractSARLQuickfixTest.assertQuickFix(AbstractSARLQuickfixTest.java:174)
	at io.sarl.lang.ui.tests.quickfix.PackageDeclarationQuickfixTest.fixPackageName(PackageDeclarationQuickfixTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:66)
	at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness.lambda$0(PlatformUITestHarness.java:43)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4528)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4146)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:52)
	at org.eclipse.pde.internal.junit.runtime.UITestApplication.runApp(UITestApplication.java:43)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:46)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
	Suppressed: org.eclipse.xtext.formatting2.internal.RegionTrace: newLine=1
		at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.add(ArrayListTextSegmentSet.java:37)
		... 73 more
	Suppressed: org.eclipse.xtext.formatting2.internal.RegionTrace: newLine=2
		at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.insertAtIndex(ArrayListTextSegmentSet.java:78)
		at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.add(ArrayListTextSegmentSet.java:45)
		at org.eclipse.xtext.formatting2.internal.FormattableDocument.addReplacer(FormattableDocument.java:73)
		at org.eclipse.xtext.formatting2.internal.FormattableDocument.set(FormattableDocument.java:310)
		at org.eclipse.xtext.formatting2.internal.FormattableDocument.append(FormattableDocument.java:83)
		at org.eclipse.xtend.core.formatting2.XtendFormatter._format(XtendFormatter.java:129)
		... 69 more
Caused by: org.eclipse.xtext.formatting2.ConflictingFormattingException: Conflicting values for 'newLineMin': '2' and '1'.
	at org.eclipse.xtext.formatting2.internal.HiddenRegionFormatting.merge(HiddenRegionFormatting.java:102)
	at org.eclipse.xtext.formatting2.internal.HiddenRegionFormatting.mergeValuesFrom(HiddenRegionFormatting.java:111)
	at org.eclipse.xtext.formatting2.internal.HiddenRegionFormattingMerger.merge(HiddenRegionFormattingMerger.java:32)
	at org.eclipse.xtext.formatting2.internal.HiddenRegionFormattingMerger.merge(HiddenRegionFormattingMerger.java:1)
	at org.eclipse.xtext.formatting2.internal.TextReplacerMerger.mergeHiddenRegionReplacers(TextReplacerMerger.java:73)
	at org.eclipse.xtext.formatting2.internal.TextReplacerMerger.merge(TextReplacerMerger.java:36)
	at org.eclipse.xtext.formatting2.internal.TextReplacerMerger.merge(TextReplacerMerger.java:1)
	at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.replaceExistingEntry(ArrayListTextSegmentSet.java:120)
	... 74 more
```

**Comment by gallandarakhneorg** [comment]
This issue is not blocking.
