### ISSUE TITLE
Bug on Eclipse in the last version of Mac OSX Sierra

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#512]
!ENTRY org.eclipse.osgi 4 0 2016-09-20 10:35:49.794
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:78)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by gallandarakhneorg** [comment]
Is it version 0.4.1?

**Comment by ngaud** [comment]
Yes 0.4.1 current stable release

**Comment by gallandarakhneorg** [comment]
Is this issue solved after launching the SARL product with:
```
eclipse-sarl -clean
```

**Comment by gallandarakhneorg** [comment]
Cannot reproduce.
