### ISSUE TITLE
Runtime error when killing agent

### ISSUE THREAD

**Issue by Lomadriel** [sarl/sarl#525]
```
[SEVERE, 4:25:54pm, null] Uncaught exception: Missing for a method annotated with @PerceptGuardEvaluator. Is Environment [id = 5b5d3481-8795-4258-813d-aed2db672f92, parentID=2c38fb7f-f363-4f6e-877b-110b1f07cc77] registered?
in thread #1119 'pool-1-thread-1121'.
java.lang.IllegalArgumentException: Missing for a method annotated with @PerceptGuardEvaluator. Is Environment [id = 5b5d3481-8795-4258-813d-aed2db672f92, parentID=2c38fb7f-f363-4f6e-877b-110b1f07cc77] registered?
    at io.janusproject.kernel.bic.internaleventdispatching.BehaviorGuardEvaluatorRegistry.unregister(BehaviorGuardEvaluatorRegistry.java:165)
    at io.janusproject.kernel.bic.internaleventdispatching.AgentInternalEventsDispatcher.unregister(AgentInternalEventsDispatcher.java:118)
    at io.janusproject.kernel.bic.InternalEventBusSkill.uninstall(InternalEventBusSkill.java:136)
    at sun.reflect.GeneratedMethodAccessor898.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at io.janusproject.kernel.bic.AgentLifeCycleSupport.uninstallSkills(AgentLifeCycleSupport.java:191)
    at io.janusproject.kernel.bic.AgentLifeCycleSupport.agentDestroy(AgentLifeCycleSupport.java:105)
    at io.janusproject.kernel.services.jdk.spawn.StandardSpawnService.fireAgentDestroyed(StandardSpawnService.java:373)
    at io.janusproject.kernel.services.jdk.spawn.StandardSpawnService.killAgent(StandardSpawnService.java:186)
    at io.janusproject.kernel.bic.InternalEventBusSkill$AgentEventListener.killOwner(InternalEventBusSkill.java:283)
    at io.janusproject.kernel.bic.InternalEventBusSkill$AgentEventListener.killOrMarkAsKilled(InternalEventBusSkill.java:293)
    at io.janusproject.kernel.bic.InternalEventBusSkill.selfEvent(InternalEventBusSkill.java:195)
    at io.janusproject.kernel.bic.LifecycleSkill.killMe(LifecycleSkill.java:83)
    at io.sarl.demos.gameoflife.environment.agent.Environment.$behaviorUnit$GameIsDead$5(Environment.java:186)
    at io.sarl.demos.gameoflife.environment.agent.Environment.lambda$5(Environment.java:290)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by gallandarakhneorg** [comment]
I have commented out a part of the unregistration code because I do not understand its behavior (two calls to the removeAll functions).

@ngaud please fix my patch according to the initial intention of the code.
