### ISSUE TITLE
Error when compiling from CLI with 0.4.2 (and 0.5.0-SNAPSHOT) but produces binaries anyway

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#532]
We are now using the 0.4.2 version to compile our SARL elevator controller application and we get tons of errors when compiling in CLI, though in the end the binaries are produced.

I ran this: `mvn clean compile`

First it gives this error many times:

```
[INFO] Generating the Java model elements
1    [main] ERROR clipse.xtext.util.ExceptionAcceptor  - 
java.lang.NullPointerException
	at org.eclipse.xtext.formatting2.regionaccess.internal.AbstractTextSegment.contains(AbstractTextSegment.java:47)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.addReplacer(FormattableDocument.java:61)
	at org.eclipse.xtext.xbase.formatting2.XbaseFormatter._format(XbaseFormatter.java:284)
	at org.eclipse.xte
O] Generating the Java model elements
1    [main] ERROR clipse.xtext.util.ExceptionAcceptor  - 
java.lang.NullPointerException
	at org.eclipse.xtext.formatting2.regionaccess.internal.AbstractTextSegment.contains(AbstractTextSegment.java:47)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.addReplacer(FormattableDocument.java:61)
	at org.eclipse.xtext.xbase.formatting2.XbaseFormatter._format(XbaseFormatter.java:284)
	at org.eclipse.xtend.core.formatting2.XtendFormatter.format(XtendFormatter.java:831)
	at io.sarl.lang.formatting2.SARLFormatter.format(SARLFormatter.java:19)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:180)
	at io.sarl.lang.formatting2.SARLFormatter._format(SARLFormatter.java:309)
	at org.eclipse.xtend.core.formatting2.XtendFormatter.format(XtendFormatter.java:795)
	at io.sarl.lang.formatting2.SARLFormatter.format(SARLFormatter.java:19)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:180)
	at io.sarl.lang.formatting2.SARLFormatter.formatBody(SARLFormatter.java:627)
	at io.sarl.lang.formatting2.SARLFormatter._format(SARLFormatter.java:251)
	at io.sarl.lang.formatting2.SARLFormatter.format(SARLFormatter.java:161)

```

and then many of this sort:

```
272  [main] ERROR clipse.xtext.util.ExceptionAcceptor  - org.eclipse.xtext.xbase.impl.XMemberFeatureCallImplCustom cannot be cast to org.eclipse.xtext.xbase.XBinaryOperation
java.lang.ClassCastException: org.eclipse.xtext.xbase.impl.XMemberFeatureCallImplCustom cannot be cast to org.eclipse.xtext.xbase.XBinaryOperation
	at org.eclipse.xtext.xbase.formatting2.XbaseFormatter._format(XbaseFormatter.java:723)
	at org.eclipse.xtend.core.formatting2.XtendFormatter.format(XtendFormatter.java:807)
	at io.sarl.lang.formatting2.SARLFormatter.format(SARLFormatter.java:19)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:180)
	at io.sarl.lang.formatting2.SARLFormatter._format(SARLFormatter.java:468)
	at io.sarl.lang.formatting2.SARLFormatter.format(SARLFormatter.java:167)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:180)
	at io.sarl.lang.formatting2.SARLFormatter.formatBody(SARLFormatter.java:627)

```

Using  this on Linux:

```
    <properties>
        <janus.version>2.0.4.2</janus.version>
        <sarl.version>0.4.2</sarl.version>
        <json.version>20160810</json.version>
        <compiler.level>1.8</compiler.level>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        </properties>
```

Happy to help and provide more info if needed. Maybe this is something known/seen already with 0.4.2?

Cheers

Sebastian

**Comment by gallandarakhneorg** [comment]
The errors are generated by the code formater for formatting the generated Java code.
They are not causing a stop of the compiler, and the Java code should be generated and compiler.

Nevertheless, this issue will be fixed for avoiding annoying messages.

**Comment by ssardina** [comment]
Indeed, you are totally right, as I said the binaries are produced in the end so the compiler is not stopped. Good to know what was the root of it. I agree that it would be good to fix it, it looks puzzling and worrying for the non SARL expert :-)

**Comment by gallandarakhneorg** [comment]
Dear @ssardina.
If you have detected a SARL file for which the errors occurs systematically, could you send it to me in order to reproduce the issue as soon as possible?

**Comment by ssardina** [comment]
HI @gallandarakhneorg 

Sure, we are now comfortable releasing our SARL project:

https://bitbucket.org/sarlrmit/sarl-controller

If you clone that and try to compile it from CLI you will see the errors.

Hope that helps

Sebastian

**Comment by gallandarakhneorg** [comment]
Hi @ssardina 
Thank's great. I will use your project for solving the formatting issues.

Do you accept to put a link to your project in the SARL success stories (in the README file and on the community page of sarl.io)?

All the best.
Stéphane.

**Comment by ssardina** [comment]
Hi Stephane,

Of course, happy that you do that.

See the project mostly has the *infrastructure* to connect SARL to our Elevator Simulator (which is an extension of an existing simulator), that is, the SARL "skill". Said so there are some simple SARL controllers too, but the idea is to develop more controllers.

So, yes, we are happy that you mention our project.

Thanks,

Sebastian
