### ISSUE TITLE
Error during documentation generation.

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#541]
When generating the documentation with Jnario, the following error message is logged. This error does not cause a generation failure.

```
Running io.sarl.docs.faq.SARLSyntaxFAQGeneralSyntaxSpec
21449 [main] ERROR base.resource.BatchLinkableResource  - generation context cannot be found for: io.sarl.docs.faq.syntax.A$__A
java.lang.IllegalStateException: generation context cannot be found for: io.sarl.docs.faq.syntax.A$__A
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.getContext(SARLJvmModelInferrer.java:371)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.transform(SARLJvmModelInferrer.java:1195)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer.transform(XtendJvmModelInferrer.java:565)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.transform(SARLJvmModelInferrer.java:1058)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer.inferLocalClass(XtendJvmModelInferrer.java:847)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer.initializeLocalTypes(XtendJvmModelInferrer.java:821)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer.setBody(XtendJvmModelInferrer.java:646)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.setBody(SARLJvmModelInferrer.java:295)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.transform(SARLJvmModelInferrer.java:1303)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer.transform(XtendJvmModelInferrer.java:565)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.transform(SARLJvmModelInferrer.java:1058)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.appendAOPMembers(SARLJvmModelInferrer.java:1873)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer.initialize(SARLJvmModelInferrer.java:666)
	at io.sarl.lang.jvmmodel.SARLJvmModelInferrer$2.run(SARLJvmModelInferrer.java:396)
	at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer$3.run(XtendJvmModelInferrer.java:217)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.ensureJvmMembersInitialized(BatchLinkableResource.java:231)
```

**Comment by gallandarakhneorg** [comment]
See #576.
