### ISSUE TITLE
Exception when killing an agent

### ISSUE THREAD

**Issue by MrFouss** [sarl/sarl#624]
The exception is sometimes thrown for Agent2 or Agent3.

```
[SEVERE, 11:08:42am, Janus SRE] Cannot kill the agent b55c6ea7-8301-4ea4-a9ba-1c15fc5d994d: io.janusproject.services.spawn.SpawnService$AgentKillException: Cannot kill the agent 'b55c6ea7-8301-4ea4-a9ba-1c15fc5d994d'
io.janusproject.services.spawn.SpawnService$AgentKillException: Cannot kill the agent 'b55c6ea7-8301-4ea4-a9ba-1c15fc5d994d'
	at io.janusproject.kernel.services.jdk.spawn.StandardSpawnService.killAgent(StandardSpawnService.java:298)
	at io.janusproject.kernel.bic.InternalEventBusSkill$AgentEventListener.killOwner(InternalEventBusSkill.java:396)
	at io.janusproject.kernel.bic.InternalEventBusSkill$AgentEventListener.killOrMarkAsKilled(InternalEventBusSkill.java:407)
	at io.janusproject.kernel.bic.InternalEventBusSkill.selfEvent(InternalEventBusSkill.java:302)
	at io.janusproject.kernel.bic.LifecycleSkill.killMe(LifecycleSkill.java:143)
	at fr.utbm.info.ia51.labwork1.getting_started.Agent3.$behaviorUnit$Hello$1(Agent3.java:45)
	at fr.utbm.info.ia51.labwork1.getting_started.Agent3.lambda$1(Agent3.java:106)
	at io.janusproject.services.executor.JanusRunnable.run(JanusRunnable.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Failing code is:
```
agent Agent1 {
	uses Logging, DefaultContextInteractions, Lifecycle

	on Initialize {
		println("Hello World!")
		info("Hello World!")
		spawn(Agent2)
		var agent3 = spawn(Agent3)
		
		emit(new Hello)
		emit(new Hello, Scopes::addresses(defaultSpace.getAddress(agent3)))
		
		killMe
	}
}

agent Agent2 {
	uses Logging, Lifecycle, SayHello

	on Initialize {
		info("Hello World!")
		setSkill(new SayHelloSkill)
	}
	
	on Hello {
		info("Good morning, my good sir!")
		sayHello
		killMe
	}
}

agent Agent3 {
	uses Logging, Lifecycle, SayHello

	on Initialize {
		info("Hello World!")
		setSkill(new DireBonjourSkill)
	}

	on Hello {
		info("M'lady !")
		sayHello
		killMe
	}
}
```

**Comment by gallandarakhneorg** [comment]
This is not a bug in the run-time environment.

You are firing two time the `Hello` events in `Agent1`.
Consequently in `Agent3`, the event handler `on Hello` is launched two times.
The first time the `killMe` function is called, it kills the agent.
The second time its is called, the run-time environment indicates that the agent was already killed by logging the exception above.
