### ISSUE TITLE
exception on killMe

### ISSUE THREAD

**Issue by Krophil** [sarl/sarl#683]
[SEVERE, 3:14:12pm, null] Uncaught exception: null
in thread #3136 'pool-3-thread-3077'.
java.lang.NullPointerException
	at io.janusproject.kernel.bic.ExternalContextAccessSkill.fireMemberLeft(ExternalContextAccessSkill.java:234)
	at io.janusproject.kernel.bic.ExternalContextAccessSkill.leave(ExternalContextAccessSkill.java:210)
	at io.janusproject.kernel.bic.ExternalContextAccessSkill.uninstall(ExternalContextAccessSkill.java:127)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.janusproject.kernel.bic.AgentLifeCycleSupport.uninstallSkillsFinalStage(AgentLifeCycleSupport.java:233)
	at io.janusproject.kernel.bic.AgentLifeCycleSupport.agentDestroy(AgentLifeCycleSupport.java:112)
	at io.janusproject.kernel.services.jdk.spawn.StandardSpawnService.fireAgentDestroyed(StandardSpawnService.java:485)
	at io.janusproject.kernel.services.jdk.spawn.StandardSpawnService.killAgent(StandardSpawnService.java:308)
	at io.janusproject.kernel.bic.InternalEventBusSkill$AgentEventListener.killOwner(InternalEventBusSkill.java:400)
	at io.janusproject.kernel.bic.InternalEventBusSkill$AgentEventListener.killOrMarkAsKilled(InternalEventBusSkill.java:408)
	at io.janusproject.kernel.bic.InternalEventBusSkill.selfEvent(InternalEventBusSkill.java:307)
	at io.janusproject.kernel.bic.LifecycleSkill.killMe(LifecycleSkill.java:143)
	at fr.utbm.info.ia51.crowdproject.agent.Animat.$behaviorUnit$EndOfSimulation$1(Animat.java:75)
	at fr.utbm.info.ia51.crowdproject.agent.Animat.lambda$1(Animat.java:116)
	at io.janusproject.services.executor.JanusRunnable.runWithEarlyExitSupport(JanusRunnable.java:69)
	at io.janusproject.services.executor.JanusRunnable.run(JanusRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by gallandarakhneorg** [comment]
This issue will be implicitly fixed wihtin Issue #751.
