### ISSUE TITLE
CLI Compile error when using occurrence.xxxx

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#850]
**Describe the bug**

Maven SARL compiles throws error on CLI when using occurrence.xxxx inside arguments (sometimes)!
(compiles well in SARL)

**To Reproduce**

This lines yields error at compile time:

`prologAssert("request(@I, @S)", occurrence.floor, occurrence.direction.toString().toLowerCase())
`
however, this works well:

```
val x = occurrence.direction.toString().toLowerCase()
prologAssert("request(@I, @S)", occurrence.floor, x)

```

Even this simpler code throws this error:

```
on CarRequestPercept {
	reportMessage("Car requested at floor :{0}, direction {1}", occurrence.floor, occurrence.direction)
}
```

but this works well:

```
on CarRequestPercept {
	val dir = occurrence.direction
	reportMessage("Car requested at floor :{0}, direction {1}", occurrence.floor, dir)
}
```

**Expected behavior**

Compile with no error.

Observe code compiles perfectly in ECLIPSE!

**Screenshots**

This is the error I get when doing `mvn clean package`. I couldn't figure out from the error what the problem was, just had to do trial error in code until I identified the ugly line.

```
[WARNING] Discouraged use of occurrence in a not read-only context. [/home/ssardina/git/soft/ELEVATOR/sarl-elevator/aopd18/sarl-elevatorsim-base-theo.git/src/main/sarl/task3/controllers/RequestDispatcher.sarl:64]
1    [main] ERROR text.validation.CompositeEValidator  - Error executing EValidator
org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=3, size=3
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)
	at io.sarl.lang.validation.SARLValidator.checkUnmodifiableEventAccess(SARLValidator.java:2282)
	at io.sarl.lang.validation.SARLValidator.checkUnmodifiableEventAccess(SARLValidator.java:2334)
	at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:118)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:312)
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:151)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.xtext.validation.CancelableDiagnostician.validate(CancelableDiagnostician.java:39)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)
	at org.eclipse.xtext.validation.CancelableDiagnostician.doValidateContents(CancelableDiagnostician.java:70)
	at org.eclipse.xtext.xbase.validation.XbaseDiagnostician.doValidateContents(XbaseDiagnostician.java:46)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.xtext.validation.CancelableDiagnostician.validate(CancelableDiagnostician.java:39)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)
	at org.eclipse.xtext.validation.CancelableDiagnostician.doValidateContents(CancelableDiagnostician.java:70)
	at org.eclipse.xtext.xbase.validation.XbaseDiagnostician.doValidateContents(XbaseDiagnostician.java:46)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.xtext.validation.CancelableDiagnostician.validate(CancelableDiagnostician.java:39)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:120)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:146)
	at org.eclipse.xtext.xbase.annotations.validation.DerivedStateAwareResourceValidator.validate(DerivedStateAwareResourceValidator.java:32)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at org.eclipse.xtend.core.validation.CachingResourceValidatorImpl.lambda$validate$0(CachingResourceValidatorImpl.java:70)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtend.core.validation.CachingResourceValidatorImpl.validate(CachingResourceValidatorImpl.java:72)
	at io.sarl.lang.compiler.batch.SarlBatchCompiler.validate(SarlBatchCompiler.java:1226)
	at io.sarl.lang.compiler.batch.SarlBatchCompiler.compile(SarlBatchCompiler.java:1043)
	at io.sarl.lang.compiler.batch.SarlBatchCompiler.compile(SarlBatchCompiler.java:956)
	at io.sarl.maven.compiler.AbstractSarlBatchCompilerMojo.compile(AbstractSarlBatchCompilerMojo.java:206)
	at io.sarl.maven.compiler.CompileMojo.compileSARL(CompileMojo.java:331)
	at io.sarl.maven.compiler.CompileMojo.executeMojo(CompileMojo.java:183)
	at io.sarl.maven.compiler.AbstractSarlMojo.execute(AbstractSarlMojo.java:120)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
49   [main] ERROR text.validation.CompositeEValidator  - Error executing EValidator

```

**System configuration:**
-- SARL version:	
-- SARL compiler:	
-  - [] Eclipse compiler without Maven	
-  - [ ] Eclipse compiler with Maven	
-  - [x] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	1.8
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Linux 32bits	
-  - [ ] Windows 64bits	
-  - [ ] Windows 32bits	
-  - [ ] MacOS 64bits	

**Additional context**

**Comment by gallandarakhneorg** [comment]
Have you a `pom` file that is similar to:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<groupId>@GROUP_ID@</groupId>
	<artifactId>@PROJECT_NAME@</artifactId>
	<version>@PROJECT_VERSION@</version>

	<properties>
		<sarl.version>0.8.0-SNAPSHOT</sarl.version>
		<compiler.level>1.8</compiler.level>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>io.sarl.maven</groupId>
			<artifactId>io.sarl.maven.sdk</artifactId>
			<version>${sarl.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.2</version>
				<configuration>
					<source>${compiler.level}</source>
					<target>${compiler.level}</target>
					<encoding>${project.build.sourceEncoding}</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>io.sarl.maven</groupId>
				<artifactId>sarl-maven-plugin</artifactId>
				<version>${sarl.version}</version>
				<extensions>true</extensions>
				<configuration>
					<source>${compiler.level}</source>
					<target>${compiler.level}</target>
					<encoding>${project.build.sourceEncoding}</encoding>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
```

The version of the `maven-compiler-plugin` should not be higher because the newer versions are using Java 1.9. And, it may cause problems during the compilation process.

**Comment by gallandarakhneorg** [comment]
This issue seems to be fixed by #847.

**Comment by ssardina** [comment]
mmm interesting because I do not have that plugin at all Stephane. This is the pom.xml for that system:


```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>rmit.agtgrp.sarl</groupId>
	<artifactId>sarl-elevatorsim-theo</artifactId>
	<version>1.0.0.7.2</version>


    <name>SARL Elevator Controller Base Framework</name>
    <description>This is a base template to build SARL controllers for the Elevator Simulator. It includes the connectivity to the simulator via the SARL Elevator Simulator Middleware and the SWI-Prolog Capacity/Skill.</description>


    <properties>
        <!-- SARL framework version and configuration -->
        <sarl.version>0.7.2</sarl.version>

        <!-- Janus project version -->
        <janus.version>2.${sarl.version}</janus.version>

        <!-- JSON version -->
        <json.version>20160810</json.version>

        <!-- Java compiler version to be used -->
        <compiler.level>1.8</compiler.level>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- SARL Elevator Controller framework version -->
        <sarl-elevatorsim-mw.version>1.1.${sarl.version}</sarl-elevatorsim-mw.version>
        
        <!-- Mochalog framework version -->
        <mochalog.version>ffe16e8</mochalog.version>
        <!-- <mochalog.version>f03a9d1</mochalog.version> -->

        <!-- SARL Prolog KB Capability version -->
        <sarl-prolog-cap.version>1.1.${sarl.version}</sarl-prolog-cap.version>

    </properties>
    

    <dependencies>
        <!-- Janus Project kernel (contains SARL language core) -->
        <dependency>
            <groupId>io.janusproject</groupId>
            <artifactId>io.janusproject.kernel</artifactId>
            <version>${janus.version}</version>
        </dependency>

        <!--  JSON framework -->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>${json.version}</version>
        </dependency>

        <!--  SARL Elevator Control framework -->
		<dependency>
		    <groupId>org.bitbucket.ssardina-research</groupId>
		    <artifactId>sarl-elevatorsim-mw</artifactId>
	    	<version>${sarl-elevatorsim-mw.version}</version>
		</dependency>

        <!--  SARL Prolog KB Capability -->
        <dependency>
            <groupId>org.bitbucket.ssardina-research</groupId>
            <artifactId>sarl-prolog-cap</artifactId>
            <version>${sarl-prolog-cap.version}</version>
        </dependency>


        <!--  Mochalog interface for SWI-Prolog -->
        <dependency>
            <groupId>com.github.ssardina</groupId>
            <artifactId>mochalog</artifactId>
            <version>${mochalog.version}</version>
        </dependency>



        
		<!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
		<dependency>
		    <groupId>org.apache.commons</groupId>
		    <artifactId>commons-lang3</artifactId>
		    <version>3.7</version>
		</dependency>
        
        
        
    </dependencies>



	<repositories>
        <!-- Janus Project kernel (contains SARL language core) -->
	  <repository>
	    <id>io.sarl-maven</id>
	    <name>SARL Snapshots</name>
	    <url>http://maven.sarl.io/</url>
	  </repository>
	  
        <!-- JitPack used for remote installation of dependencies from Github and Bitbucket -->
	    <repository>
	        <id>jitpack.io</id>
	        <name>JitPack Repository</name>
	        <url>https://jitpack.io</url>
	    </repository>

	</repositories>
	
	
	<pluginRepositories>
	  <pluginRepository>
	    <id>io.sarl-maven</id>
	    <name>SARL Snapshots</name>
	    <url>http://maven.sarl.io/</url>
	    <snapshots>
	      <enabled>true</enabled>
	    </snapshots>
	  </pluginRepository>
	</pluginRepositories>


    <!-- Build pipeline plugins -->
    <build>
        <plugins>
            <plugin>
                <groupId>io.sarl.maven</groupId>
                <artifactId>sarl-maven-plugin</artifactId>
                <version>${sarl.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <source>${compiler.level}</source>
                    <target>${compiler.level}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
        
		    <plugin>
		    <artifactId>maven-assembly-plugin</artifactId>
		    <configuration>
		        <archive>
		            <manifest>
		                <addClasspath>true</addClasspath>
		                <!--
		                <mainClass>io.janusproject.Boot</mainClass>
		                -->
		                <mainClass>BootMAS</mainClass>
		            </manifest>
		        </archive>
		        <descriptorRefs>
		            <descriptorRef>jar-with-dependencies</descriptorRef>
		        </descriptorRefs>
		    </configuration>
		    <executions>
		        <execution>
		            <id>make-my-jar-with-dependencies</id>
		            <phase>package</phase>
		            <goals>
		                <goal>single</goal>
		            </goals>
		        </execution>
		    </executions>
		    </plugin>


            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <mainClass>io.janusproject.Boot</mainClass>
                </configuration>
            </plugin>


		</plugins>
        
    </build>
</project>

```

**Comment by gallandarakhneorg** [comment]
The current state of you pom file is correct.

The `maven-compiler-plugin` is not mandatory at all because Maven is supposed to download one when needed for compilation.
If you encounter strange error related to the use of an Java 9 class from the Google library, then you have to specify the `maven-compiler-plugin` in order to avoid it.
