### ISSUE TITLE
Could not resolve module: org.eclipse.epp.mpc.core.win32

### ISSUE THREAD

**Issue by martin-utbm** [sarl/sarl#916]
**Description of your issue:**

Tried to run the SARL product as an _Eclipse-ception_ and got this error about Win32 not being found or something. Note that it doesn't prevent the SARL product from happily launching despite all.

```
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.epp.mpc.core.win32 [144]
  Unresolved requirement: Import-Package: com.sun.jna; version="4.1.0"

	at org.eclipse.osgi.container.Module.start(Module.java:452)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1784)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1763)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1726)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1657)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)
```

**System configuration:**
-- SARL version:	
-- SARL compiler:	
-  - [x] Eclipse compiler without Maven	
-  - [ ] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	`jdk1.8.0_181`
-- Operating System:	
-  - [ ] Linux 64bits	
-  - [ ] Linux 32bits	
-  - [x] Windows 64bits	
-  - [ ] Windows 32bits	
-  - [ ] MacOS 64bits

**Comment by gallandarakhneorg** [comment]
This issue should not avoid to use the SARL product. Only the Eclipse Market Place Client (MPC) should be influenced. It may cause issues for installing new plugins into the product.

However, the SARL product is not any more supported 32 bit architectures.
Could you provide use the configuration of your system by copying and pasting the content of the windows:
* Menu "Help"
* Selection menu item "About SARL Product"
* Click on "Installation Details"
* Open the tab "Configuration"
* Click on "Copy to Clipboard"

**Comment by martin-utbm** [comment]
Sure: https://gist.github.com/martin-utbm/89c621a42fcebc903b15b7c4966a1bec

**Comment by alexandrelombard** [comment]
I'm not able to reproduce this issue using the last version of the SARL product (using Win32 x86_64).

**Comment by gallandarakhneorg** [comment]
If someone as additional inputs related to this issue, please re-open it and submit the information.
