### ISSUE TITLE
NPE when firing ParticipantLeft

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#946]
In the Fireworks demo, the following exception is shown:
```
[GRAVE, 7:04:33am, Janus SRE] Uncaught exception: null
in thread #27 'pool-3-thread-9'.
java.lang.NullPointerException
	at io.janusproject.kernel.space.EventSpaceImpl.fireParticipantLeft(EventSpaceImpl.java:106)
	at io.janusproject.kernel.space.EventSpaceImpl.unregister(EventSpaceImpl.java:80)
	at io.janusproject.kernel.bic.ExternalContextAccessSkill.leave(ExternalContextAccessSkill.java:244)
	at io.janusproject.kernel.bic.ExternalContextAccessSkill.uninstall(ExternalContextAccessSkill.java:143)
	at io.sarl.lang.core.SREutils.doSkillUninstallation(SREutils.java:234)
	at io.janusproject.kernel.bic.AgentLifeCycleSupport.uninstallSkillsFinalStage(AgentLifeCycleSupport.java:198)
	at io.janusproject.kernel.bic.AgentLifeCycleSupport.agentDestroy(AgentLifeCycleSupport.java:105)
	at io.janusproject.kernel.services.jdk.spawn.StandardSpawnService.fireAgentKilled(StandardSpawnService.java:541)
	at io.janusproject.kernel.services.jdk.spawn.StandardSpawnService.killAgent(StandardSpawnService.java:320)
	at io.janusproject.services.spawn.SpawnService.killAgent(SpawnService.java:66)
	at io.janusproject.kernel.bic.InternalEventBusSkill$AgentEventListener.killOwner(InternalEventBusSkill.java:426)
	at io.janusproject.kernel.bic.InternalEventBusSkill$AgentEventListener.killOrMarkAsKilled(InternalEventBusSkill.java:434)
	at io.janusproject.kernel.bic.InternalEventBusSkill.selfEvent(InternalEventBusSkill.java:330)
	at io.janusproject.kernel.bic.LifecycleSkill.killMe(LifecycleSkill.java:161)
	at io.sarl.demos.fireworks.agents.Rocket.$behaviorUnit$MemberLeft$6(Rocket.java:226)
	at io.sarl.demos.fireworks.agents.Rocket.lambda$2(Rocket.java:357)
	at io.janusproject.services.executor.JanusRunnable.runWithEarlyExitSupport(JanusRunnable.java:69)
	at io.janusproject.services.executor.JanusRunnable.run(JanusRunnable.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gallandarakhneorg** [comment]
The concerned SRE is not the version for the next release. We will move to Janus v3.
