### ISSUE TITLE
NullpointerException when getting Executor in Eventbus

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#975]
getExecutor from EventBus return sometimes a null references. It could be linked the nullpointerexception we obtain sometimes when getting the logging capacities.

java.lang.AssertionError
	at io.sarl.sre.skills.internal.EventBus.getExecutor(EventBus.java:117)
	at io.sarl.sre.skills.internal.EventBus.asyncDispatch(EventBus.java:328)
	at io.sarl.sre.skills.internal.InternalEventBusSkill.fireEvent(InternalEventBusSkill.java:364)
	at io.sarl.sre.skills.internal.InternalEventBusSkill$ExternalEventBusAccessor.receiveEvent(InternalEventBusSkill.java:101)
	at io.sarl.sre.spaces.AbstractEventSpace.lambda$0(AbstractEventSpace.java:320)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.sarl.sre.spaces.AbstractEventSpace.emitLocally(AbstractEventSpace.java:322)
	at io.sarl.sre.spaces.AbstractEventSpace.emit(AbstractEventSpace.java:215)
	at io.sarl.sre.internal.SpaceParticipantEventEmitter.participantJoined(SpaceParticipantEventEmitter.java:75)
	at io.sarl.sre.spaces.AbstractEventSpace.registerToSpace(AbstractEventSpace.java:134)
	at io.sarl.sre.spaces.OpenLocalEventSpace.register(OpenLocalEventSpace.java:60)
	at io.sarl.sre.services.lifecycle.AgentLife.attachAgentToPlatform(AgentLife.java:284)
	at io.sarl.sre.services.lifecycle.AgentLife.start(AgentLife.java:213)
	at io.sarl.sre.services.lifecycle.AbstractLifecycleService.lambda$4(AbstractLifecycleService.java:251)
	at io.sarl.sre.services.lifecycle.AbstractLifecycleService.spawnAgent(AbstractLifecycleService.java:284)
	at io.sarl.sre.services.lifecycle.AbstractLifecycleService.spawnAgent(AbstractLifecycleService.java:218)
	at io.sarl.sre.skills.bic.LifecycleSkill.spawn(LifecycleSkill.java:102)
	at io.sarl.scalability.tests.BootScalableAgent.$behaviorUnit$Initialize$0(BootScalableAgent.java:36)
	at io.sarl.scalability.tests.BootScalableAgent.lambda$0(BootScalableAgent.java:78)
	at io.sarl.sre.services.executor.SreRunnable.protectRun(SreRunnable.java:93)
	at io.sarl.sre.services.executor.SreRunnable.runWithEarlyExitSupport(SreRunnable.java:121)
	at io.sarl.sre.services.executor.SreRunnable.run(SreRunnable.java:86)
	at io.sarl.sre.skills.internal.EventBus.executeBehaviorMethodsInParalellWithSynchroAtTheEnd(EventBus.java:538)
	at io.sarl.sre.skills.internal.EventBus.immediateDispatch(EventBus.java:223)
	at io.sarl.sre.skills.internal.InternalEventBusSkill.fireEventAndWait(InternalEventBusSkill.java:338)
	at io.sarl.sre.services.lifecycle.AgentLife.start(AgentLife.java:216)
	at io.sarl.sre.services.lifecycle.AbstractLifecycleService.lambda$4(AbstractLifecycleService.java:251)
	at io.sarl.sre.services.lifecycle.AbstractLifecycleService.spawnAgent(AbstractLifecycleService.java:284)
	at io.sarl.sre.services.lifecycle.AbstractLifecycleService.spawnAgent(AbstractLifecycleService.java:218)
	at io.sarl.sre.Kernel.spawn(Kernel.java:272)
	at io.sarl.sre.boot.SreMain.startAgent(SreMain.java:433)
	at io.sarl.sre.boot.commands.AbstractRunCommand.startAgentsFromConfig(AbstractRunCommand.java:193)
	at io.sarl.sre.boot.commands.RunSingleAgentCommand.run(RunSingleAgentCommand.java:77)
	at io.bootique.run.DefaultRunner.run(DefaultRunner.java:43)
	at io.bootique.BQRuntime.run(BQRuntime.java:85)
	at io.sarl.sre.boot.SreMain.runSRE(SreMain.java:244)
	at io.sarl.sre.boot.Boot.main(Boot.java:83)

**Comment by ngaud** [comment]
Reproducible on SARL Benchmark https://github.com/sarl/SARLBenchmarks/
