### ISSUE TITLE
UnimplementedCapacityException when getting logging capacity

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#976]
Sometimes the 
Logging _$CAPACITY_USE$IO_SARL_CORE_LOGGING$CALLER = this.$castSkill(Logging.class, (this.$CAPACITY_USE$IO_SARL_CORE_LOGGING == null || this.$CAPACITY_USE$IO_SARL_CORE_LOGGING.get() == null) ? (this.$CAPACITY_USE$IO_SARL_CORE_LOGGING = this.$getSkill(Logging.class)) : this.$CAPACITY_USE$IO_SARL_CORE_LOGGING);
        this.eventBus.asyncDispatch(event, _$CAPACITY_USE$IO_SARL_CORE_LOGGING$CALLER.getLogger());

in InternalEventBusSkill.freEvent return a null loggin capacity but it shouldn't.

io.sarl.lang.core.UnimplementedCapacityException: io.sarl.core.Logging
	at io.sarl.lang.core.AgentTrait.$castSkill(AgentTrait.java:116)
	at io.sarl.sre.skills.internal.InternalEventBusSkill.fireEvent(InternalEventBusSkill.java:363)
	at io.sarl.sre.skills.internal.InternalEventBusSkill$ExternalEventBusAccessor.receiveEvent(InternalEventBusSkill.java:101)
	at io.sarl.sre.spaces.AbstractEventSpace.lambda$0(AbstractEventSpace.java:320)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.sarl.sre.spaces.AbstractEventSpace.emitLocally(AbstractEventSpace.java:322)
	at io.sarl.sre.spaces.AbstractEventSpace.emit(AbstractEventSpace.java:215)
	at io.sarl.sre.skills.bic.DefaultContextInteractionsSkill.emit(DefaultContextInteractionsSkill.java:116)
	at io.sarl.core.DefaultContextInteractions.emit(DefaultContextInteractions.java:238)
	at io.sarl.scalability.tests.ScalableAgent.$behaviorUnit$Taskgo$1(ScalableAgent.java:50)
	at io.sarl.scalability.tests.ScalableAgent.lambda$2(ScalableAgent.java:116)
	at io.sarl.sre.skills.bic.SchedulesSkill.lambda$1(SchedulesSkill.java:1011)
	at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.coreRun(SchedulesSkill.java:370)
	at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.run(SchedulesSkill.java:411)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by gallandarakhneorg** [comment]
What is the demo, which may enable me to reproduce?

**Comment by ngaud** [comment]
SARL Benchmark https://github.com/sarl/SARLBenchmarks/
