### ISSUE TITLE
M2E plugin create `src/main/*` folders in Eclipse plugins.

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#979]
When editing the SARL project, several modules are Eclipse plugins that are written in SARL, e.g. `io.sarl.core`.

The SARL M2E plugin create the standard folders `src/main/sarl` and `src/main/generated-sources/sarl` into these projects.

It causes an invalid compilation, since the folder `src` is a source folder by itself.

**Comment by gallandarakhneorg** [comment]
The M2E misconfiguration may cause infinite loop in the Java compiler and JDT exceptions:
```
Java Model Exception: Java Model Status [src/main/generated-sources/sarl/io/sarl/util [in io.sarl.util] is not on its project's build path]
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getRawClasspathEntry(PackageFragmentRoot.java:613)
	at org.eclipse.jdt.core.JavaCore.getGeneratedResources(JavaCore.java:4140)
	at org.eclipse.xtext.builder.smap.DebugSourceInstallingCompilationParticipant.findGeneratedJavaClassFiles(DebugSourceInstallingCompilationParticipant.java:191)
	at org.eclipse.xtext.builder.smap.DebugSourceInstallingCompilationParticipant.buildFinished(DebugSourceInstallingCompilationParticipant.java:145)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:253)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:515)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:412)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:291)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
