### ISSUE TITLE
RuntimeException: Agent task is null in ScheduleSkill TaskRunner

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#988]
java.lang.RuntimeException: Agent task is null.
	at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.internalRun(SchedulesSkill.java:380)
	at io.sarl.sre.services.executor.SreRunnable.run(SreRunnable.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Reproducible  within the SARL BEnchmark

**Comment by ngaud** [comment]
Should not be a weakreference, since this is the only place where the task description reference is maintained
