### ISSUE TITLE
Multiple NPE on SARL Benchmark

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#989]
Done on SARL Benchmark with only 2 spawned agents and the boot agent.
Easily reproducible.

[INFOS, 4:41:54pm, BootAgent] Spawning agent 0
[INFOS, 4:41:54pm, BootAgent] Spawning agent 1
[INFOS, 4:41:55pm, 0] Initialize
[INFOS, 4:41:57pm, 1] Initialize
[INFOS, 4:42:01pm, 1] The agent was stopped.
[GRAVE, 4:42:02pm, 1] NullPointerException
java.lang.NullPointerException
	at io.sarl.sre.skills.bic.DefaultContextInteractionsSkill.getDefaultAddress(DefaultContextInteractionsSkill.java:71)
	at io.sarl.sre.skills.bic.DefaultContextInteractionsSkill.emit(DefaultContextInteractionsSkill.java:115)
	at io.sarl.core.DefaultContextInteractions.emit(DefaultContextInteractions.java:202)
	at io.sarl.scalability.tests.ScalableAgent.lambda$0(ScalableAgent.java:41)
	at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.coreRun(SchedulesSkill.java:368)
	at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.internalRun(SchedulesSkill.java:394)
	at io.sarl.sre.services.executor.SreRunnable.run(SreRunnable.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[GRAVE, 4:42:03pm, 1] NullPointerException
java.lang.NullPointerException
	at io.sarl.sre.skills.bic.DefaultContextInteractionsSkill.getDefaultAddress(DefaultContextInteractionsSkill.java:71)
	at io.sarl.sre.skills.bic.DefaultContextInteractionsSkill.emit(DefaultContextInteractionsSkill.java:115)
	at io.sarl.core.DefaultContextInteractions.emit(DefaultContextInteractions.java:202)
	at io.sarl.scalability.tests.ScalableAgent.lambda$0(ScalableAgent.java:41)
	at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.coreRun(SchedulesSkill.java:368)
	at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.internalRun(SchedulesSkill.java:394)
	at io.sarl.sre.services.executor.SreRunnable.run(SreRunnable.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ngaud** [comment]
[INFOS, 4:39:00pm, BootAgent] Spawning agent 0
[INFOS, 4:39:00pm, BootAgent] Spawning agent 1
[INFOS, 4:39:00pm, 1] Initialize
[INFOS, 4:39:00pm, 0] Initialize
[INFOS, 4:39:00pm, BootAgent] Boot dead.
[INFOS, 4:39:00pm, 0] The agent was stopped.
[INFOS, 4:39:00pm, 1] The agent was stopped.
[GRAVE, 4:39:00pm, SARL Run-time Environment] null
java.lang.NullPointerException
	at io.sarl.lang.core.SREutils.castInternalSkillReference(SREutils.java:123)
	at io.sarl.sre.services.lifecycle.AgentLife.getEventBus(AgentLife.java:167)
	at io.sarl.sre.services.lifecycle.AgentLife.stop(AgentLife.java:318)
	at io.sarl.sre.services.lifecycle.AgentLife.stop(AgentLife.java:702)
	at io.sarl.sre.services.lifecycle.AbstractLifecycleService.killAgent(AbstractLifecycleService.java:527)
	at io.sarl.sre.skills.bic.LifecycleSkill.lambda$1(LifecycleSkill.java:80)
	at io.sarl.sre.services.executor.SreRunnable.internalRun(SreRunnable.java:94)
	at io.sarl.sre.services.executor.SreRunnable.run(SreRunnable.java:102)
	at io.sarl.sre.services.executor.EarlyExitException.runPostTreatment(EarlyExitException.java:62)
	at io.sarl.sre.services.executor.SreRunnable.run(SreRunnable.java:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[INFOS, 4:39:00pm, SARL Run-time Environment] Stopping the kernel services
[INFOS, 4:39:00pm, SARL Run-time Environment] All kernel services are stopped

**Comment by gallandarakhneorg** [comment]
Seems to be fixed in my environment with more than 4000 agents.
