### ISSUE TITLE
Agent.getLife.getDefaultContext() could sometimes return null

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#993]
Reproducible in SARL Benchmark and sometimes in boids as well

[GRAVE, 11:30:10am, 132] AssertionError
java.lang.AssertionError
	at io.sarl.sre.skills.bic.DefaultContextInteractionsSkill.getDefaultAddress(DefaultContextInteractionsSkill.java:137)
	at io.sarl.sre.skills.bic.DefaultContextInteractionsSkill.emit(DefaultContextInteractionsSkill.java:288)
	at io.sarl.core.DefaultContextInteractions.emit(DefaultContextInteractions.java:202)
	at io.sarl.scalability.tests.ScalableAgent.lambda$0(ScalableAgent.java:41)
	at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.coreRun(SchedulesSkill.java:369)
	at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.internalRun(SchedulesSkill.java:404)
	at io.sarl.sre.services.executor.SreRunnable.run(SreRunnable.java:103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ngaud** [comment]
Dire[GRAVE, 4:39:28pm, 953] AssertionError
java.lang.AssertionError
	at io.sarl.sre.skills.bic.DefaultContextInteractionsSkill.getDefaultAddress(DefaultContextInteractionsSkill.java:137)
	at io.sarl.sre.skills.bic.DefaultContextInteractionsSkill.emit(DefaultContextInteractionsSkill.java:288)
	at io.sarl.core.DefaultContextInteractions.emit(DefaultContextInteractions.java:202)
	at io.sarl.scalability.tests.ScalableAgent.lambda$0(ScalableAgent.java:41)
	at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.coreRun(SchedulesSkill.java:369)
	at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.internalRun(SchedulesSkill.java:404)
	at io.sarl.sre.services.executor.SreRunnable.run(SreRunnable.java:103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutoctly linked to

**Comment by gallandarakhneorg** [comment]
This [test](https://github.com/sarl/sarl/blob/master/sre/io.janusproject/io.janusproject.tests/src/test/sarl/io/sarl/sre/tests/runtime/bugs/bug976/Bug976Test.sarl) is based on the same code as the benchmark.
No error is output after 2 minutes of run.

**Comment by gallandarakhneorg** [comment]
Seems to be fixed on my environment.
